Controllers/ClientInfoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ehrmadesimple.Data;
using ehrmadesimple.Models;

namespace ehrmadesimple.Controllers
{
    public class ClientInfoesController : Controller
    {
        private readonly AppDbContext _context;

        public ClientInfoesController(AppDbContext context)
        {
            _context = context;
        }

        // GET: ClientInfoes
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.ClientInfoes.Include(c => c.Client);
            return View(await appDbContext.ToListAsync());
        }

        // GET: ClientInfoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientInfo = await _context.ClientInfoes
                .Include(c => c.Client)
                .FirstOrDefaultAsync(m => m.ClientInfoId == id);
            if (clientInfo == null)
            {
                return NotFound();
            }

            return View(clientInfo);
        }

        // GET: ClientInfoes/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            return View();
        }

        // POST: ClientInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientInfoId,ClientId,ClientEmail,Street,City,State,Zip,BdayMonth,BdayDay,BdayYear,Sex,RelationshipStatus,EmploymentStatus,EmergencyFname,EmergencyLname,EmergencyRelationship,EmergencyEmail,EmergencyPhone")] ClientInfo clientInfo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(clientInfo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", clientInfo.ClientId);
            return View(clientInfo);
        }

        // GET: ClientInfoes/Edit/5
        public async Task<IActionResult> Edit(string? id)
        {
            var entity = _context.ClientInfoes.FirstOrDefault(e => e.ClientId == id);  
            if (entity == null) {  
                return NotFound();
            }
            return View(entity);
        }

        // POST: ClientInfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ClientInfoId,ClientId,ClientEmail,Street,City,State,Zip,BdayMonth,BdayDay,BdayYear,Sex,RelationshipStatus,EmploymentStatus,EmergencyFname,EmergencyLname,EmergencyRelationship,EmergencyEmail,EmergencyPhone")] ClientInfo clientInfo)
        {
            if (id != clientInfo.ClientInfoId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(clientInfo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientInfoExists(clientInfo.ClientInfoId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", clientInfo.ClientId);
            return View(clientInfo);
        }

        // GET: ClientInfoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var clientInfo = await _context.ClientInfoes
                .Include(c => c.Client)
                .FirstOrDefaultAsync(m => m.ClientInfoId == id);
            if (clientInfo == null)
            {
                return NotFound();
            }

            return View(clientInfo);
        }

        // POST: ClientInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var clientInfo = await _context.ClientInfoes.FindAsync(id);
            _context.ClientInfoes.Remove(clientInfo);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientInfoExists(int id)
        {
            return _context.ClientInfoes.Any(e => e.ClientInfoId == id);
        }
    }
}

Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ehrmadesimple.Data;
using ehrmadesimple.Models;

namespace ehrmadesimple.Controllers
{
    public class ClientsController : Controller
    {
        private readonly AppDbContext _context;

        public ClientsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Clients
        public ViewResult Index(string sortOrder, string searchString)
        {
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            var clients = from s in _context.Clients select s;
            if (!String.IsNullOrEmpty(searchString)) {
                int found=0;
                var index = searchString.IndexOf(" ");
                var fname = "";
                var lname= "";
                if(index == -1) {
                    fname=searchString;
                    lname= null;
                }
                else {
                    fname= searchString.Substring(0, index);
                    lname= searchString.Substring(index);
                }
                clients = clients.Where(s => s.LastName.Contains(lname) || s.LastName.Contains(fname) || s.FirstName.Contains(lname) || s.FirstName.Contains(fname));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    clients = clients.OrderByDescending(s => s.LastName);
                    break;
                case "Date":
                    clients = clients.OrderBy(s => s.FirstJoined);
                    break;
                case "date_desc":
                    clients = clients.OrderByDescending(s => s.FirstJoined);
                    break;
                default:
                    clients = clients.OrderBy(s => s.LastName);
                    break;
            }
            return View(clients.ToList());
        }

        // GET: Clients/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }
            ViewData["Title"] = "Client Details for " + client.FirstName[0] + ". " + client.LastName;
            return View(client);
        }

        // GET: Clients/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ClientId,Email,FirstName,LastName,Phone,BillingType,Diagnosis,DiagnosisTimestamp")] Client client)
        {
            if (ModelState.IsValid)
            {
                _context.Add(client);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients.FindAsync(id);
            if (client == null)
            {
                return NotFound();
            }
            return View(client);
        }

        // POST: Clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("ClientId,Email,FirstName,LastName,Phone,BillingType,Diagnosis,DiagnosisTimestamp")] Client client)
        {
            if (id != client.ClientId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(client);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClientExists(client.ClientId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(client);
        }

        // GET: Clients/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var client = await _context.Clients
                .FirstOrDefaultAsync(m => m.ClientId == id);
            if (client == null)
            {
                return NotFound();
            }

            return View(client);
        }

        // POST: Clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var client = await _context.Clients.FindAsync(id);
            _context.Clients.Remove(client);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClientExists(string id)
        {
            return _context.Clients.Any(e => e.ClientId == id);
        }
    }
}

Views/ClientInfoes/Create.cshtml
@model ehrmadesimple.Models.ClientInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>ClientInfo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class ="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ClientEmail" class="control-label"></label>
                <input asp-for="ClientEmail" class="form-control" />
                <span asp-validation-for="ClientEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zip" class="control-label"></label>
                <input asp-for="Zip" class="form-control" />
                <span asp-validation-for="Zip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BdayMonth" class="control-label"></label>
                <input asp-for="BdayMonth" class="form-control" />
                <span asp-validation-for="BdayMonth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BdayDay" class="control-label"></label>
                <input asp-for="BdayDay" class="form-control" />
                <span asp-validation-for="BdayDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BdayYear" class="control-label"></label>
                <input asp-for="BdayYear" class="form-control" />
                <span asp-validation-for="BdayYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sex" class="control-label"></label>
                <input asp-for="Sex" class="form-control" />
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RelationshipStatus" class="control-label"></label>
                <input asp-for="RelationshipStatus" class="form-control" />
                <span asp-validation-for="RelationshipStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmploymentStatus" class="control-label"></label>
                <input asp-for="EmploymentStatus" class="form-control" />
                <span asp-validation-for="EmploymentStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyFname" class="control-label"></label>
                <input asp-for="EmergencyFname" class="form-control" />
                <span asp-validation-for="EmergencyFname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyLname" class="control-label"></label>
                <input asp-for="EmergencyLname" class="form-control" />
                <span asp-validation-for="EmergencyLname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyRelationship" class="control-label"></label>
                <input asp-for="EmergencyRelationship" class="form-control" />
                <span asp-validation-for="EmergencyRelationship" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyEmail" class="control-label"></label>
                <input asp-for="EmergencyEmail" class="form-control" />
                <span asp-validation-for="EmergencyEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyPhone" class="control-label"></label>
                <input asp-for="EmergencyPhone" class="form-control" />
                <span asp-validation-for="EmergencyPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Views/ClientInfoes/Delete.cshtml
@model ehrmadesimple.Models.ClientInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ClientInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BdayMonth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BdayMonth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BdayDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BdayDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BdayYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BdayYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sex)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RelationshipStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RelationshipStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmploymentStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmploymentStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyFname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyFname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyLname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyLname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyRelationship)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyRelationship)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ClientInfoId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/ClientInfoes/Details.cshtml
@model ehrmadesimple.Models.ClientInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>

<div>
    <h4>ClientInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClientEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClientEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Street)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Zip)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Zip)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BdayMonth)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BdayMonth)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BdayDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BdayDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BdayYear)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BdayYear)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sex)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sex)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RelationshipStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RelationshipStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmploymentStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmploymentStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyFname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyFname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyLname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyLname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyRelationship)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyRelationship)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmergencyPhone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmergencyPhone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ClientInfoId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

Views/ClientInfoes/Edit.cshtml
@model ehrmadesimple.Models.ClientInfo

@{
}

<!DOCTYPE html>

<html>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2><b>Edit <i>Address & Emergency Contact - @Html.DisplayFor(model=> model.FullName)</i> </b></h2> 
        <a asp-action="Index" asp-controller="Clients" class="goback">< Go Back</a>
    </div>
</div>
<body>
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a class="nav-link active" href="/Clients/Edit/@Model.ClientId">Basic Info</a>
    </li>
    <li class="nav-item">
        <a class="nav-link active" href="#">Address & Emergency Contact</a>
    </li>
</ul>
<div class="wrapper wrapper-content animated fadeInRight">
<div class="row">
    <div class="col-md-4">
        
        <form asp-action="Edit">
            <br>
            <div class="form-group">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Zip" class="control-label"></label>
                <input asp-for="Zip" class="form-control" />
                <span asp-validation-for="Zip" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BdayMonth" class="control-label"></label>
                <input asp-for="BdayMonth" class="form-control" />
                <span asp-validation-for="BdayMonth" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BdayDay" class="control-label"></label>
                <input asp-for="BdayDay" class="form-control" />
                <span asp-validation-for="BdayDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BdayYear" class="control-label"></label>
                <input asp-for="BdayYear" class="form-control" />
                <span asp-validation-for="BdayYear" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sex" class="control-label"></label>
                <input asp-for="Sex" class="form-control" />
                <span asp-validation-for="Sex" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RelationshipStatus" class="control-label"></label>
                <input asp-for="RelationshipStatus" class="form-control" />
                <span asp-validation-for="RelationshipStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmploymentStatus" class="control-label"></label>
                <input asp-for="EmploymentStatus" class="form-control" />
                <span asp-validation-for="EmploymentStatus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyFname" class="control-label"></label>
                <input asp-for="EmergencyFname" class="form-control" />
                <span asp-validation-for="EmergencyFname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyLname" class="control-label"></label>
                <input asp-for="EmergencyLname" class="form-control" />
                <span asp-validation-for="EmergencyLname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyRelationship" class="control-label"></label>
                <input asp-for="EmergencyRelationship" class="form-control" />
                <span asp-validation-for="EmergencyRelationship" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyEmail" class="control-label"></label>
                <input asp-for="EmergencyEmail" class="form-control" />
                <span asp-validation-for="EmergencyEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EmergencyPhone" class="control-label"></label>
                <input asp-for="EmergencyPhone" class="form-control" />
                <span asp-validation-for="EmergencyPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
</div>

@section Scripts {
@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
<script>
    function goBack() {
        window.history.back();
    }
</script>
}
</body>
</html>