Models/Appointment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Text.RegularExpressions;

namespace ehrmadesimple.Models
{
    public class Appointment
    {
        private string base64Guid = Regex.Replace(Convert.ToBase64String(Guid.NewGuid().ToByteArray()), "[/+=]", "");
        [Key]
        public string AppointmentId { get { return base64Guid; } set { base64Guid = value; } }
        [Required]
        public string Clientname { get; set; }
        [ForeignKey("Client")]
        public string ClientId { get; set; }
        [ForeignKey("Bill")]
        public string BillId {get;set;}
        public DateTime Timestamp {get;set;}
        public int Duration {get;set;}
        public bool isAllDay { get; set; }
        public string Location {get;set;}
        public bool isRepeating {get;set;}
        public string ServiceType {get;set;}
        public string ProgressNote {get;set;}
        public string PsychoNote {get;set;}
        public virtual Bill Bill { get; set; }
        public virtual Client Client { get; set; }
    }
}

Controllers/AppointmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ehrmadesimple.Data;
using ehrmadesimple.Models;

namespace ehrmadesimple.Controllers
{
    public class AppointmentsController : Controller
    {
        private readonly AppDbContext _context;

        public AppointmentsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Appointments
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Appointments.Include(a => a.Client);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Appointments/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Client)
                .FirstOrDefaultAsync(m => m.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // GET: Appointments/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            return View();
        }

        // POST: Appointments/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AppointmentId,Clientname,ClientId,Timestamp,Duration,isAllDay,Location,isRepeating,ServiceType")] Appointment appointment)
        {
            if (ModelState.IsValid)
            {
                _context.Add(appointment);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", appointment.ClientId);
            return View(appointment);
        }

        // GET: Appointments/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments.FindAsync(id);
            if (appointment == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", appointment.ClientId);
            return View(appointment);
        }

        // POST: Appointments/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("AppointmentId,Clientname,ClientId,Timestamp,Duration,isAllDay,Location,isRepeating,ServiceType")] Appointment appointment)
        {
            if (id != appointment.AppointmentId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(appointment);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AppointmentExists(appointment.AppointmentId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", appointment.ClientId);
            return View(appointment);
        }

        // GET: Appointments/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var appointment = await _context.Appointments
                .Include(a => a.Client)
                .FirstOrDefaultAsync(m => m.AppointmentId == id);
            if (appointment == null)
            {
                return NotFound();
            }

            return View(appointment);
        }

        // POST: Appointments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var appointment = await _context.Appointments.FindAsync(id);
            _context.Appointments.Remove(appointment);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AppointmentExists(string id)
        {
            return _context.Appointments.Any(e => e.AppointmentId == id);
        }
    }
}

Controllers/BillsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ehrmadesimple.Data;
using ehrmadesimple.Models;

namespace ehrmadesimple.Controllers
{
    public class BillsController : Controller
    {
        private readonly AppDbContext _context;

        public BillsController(AppDbContext context)
        {
            _context = context;
        }

        // GET: Bills
        public async Task<IActionResult> Index()
        {
            var appDbContext = _context.Bills.Include(b => b.Client);
            return View(await appDbContext.ToListAsync());
        }

        // GET: Bills/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bills
                .Include(b => b.Client)
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }
        // GET: Bills/Create
        public IActionResult Create()
        {
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId");
            return View();
        }

        // POST: Bills/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BillId,ClientId,Timestamp,Fee,isPaid,BillingType")] Bill bill)
        {
            if (ModelState.IsValid)
            {
                _context.Add(bill);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", bill.ClientId);
            return View(bill);
        }

        // GET: Bills/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bills.FindAsync(id);
            if (bill == null)
            {
                return NotFound();
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", bill.ClientId);
            return View(bill);
        }

        // POST: Bills/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("BillId,ClientId,Timestamp,Fee,isPaid,BillingType")] Bill bill)
        {
            if (id != bill.BillId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(bill);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillExists(bill.BillId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ClientId"] = new SelectList(_context.Clients, "ClientId", "ClientId", bill.ClientId);
            return View(bill);
        }

        // GET: Bills/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var bill = await _context.Bills
                .Include(b => b.Client)
                .FirstOrDefaultAsync(m => m.BillId == id);
            if (bill == null)
            {
                return NotFound();
            }

            return View(bill);
        }

        // POST: Bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var bill = await _context.Bills.FindAsync(id);
            _context.Bills.Remove(bill);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillExists(string id)
        {
            return _context.Bills.Any(e => e.BillId == id);
        }
    }
}

Views/Appointments/Create.cshtml
@model ehrmadesimple.Models.Appointment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>

<h4>Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="AppointmentId" class="control-label"></label>
                <input asp-for="AppointmentId" class="form-control" />
                <span asp-validation-for="AppointmentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Clientname" class="control-label"></label>
                <input asp-for="Clientname" class="form-control" />
                <span asp-validation-for="Clientname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class ="form-control" asp-items="ViewBag.ClientId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Timestamp" class="control-label"></label>
                <input asp-for="Timestamp" class="form-control" />
                <span asp-validation-for="Timestamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isAllDay" /> @Html.DisplayNameFor(model => model.isAllDay)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isRepeating" /> @Html.DisplayNameFor(model => model.isRepeating)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ServiceType" class="control-label"></label>
                <input asp-for="ServiceType" class="form-control" />
                <span asp-validation-for="ServiceType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>

Views/Appointments/Delete.cshtml
@model ehrmadesimple.Models.Appointment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appointment</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Clientname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Clientname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Timestamp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Timestamp)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isAllDay)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isAllDay)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.isRepeating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.isRepeating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ServiceType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Client)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Client.ClientId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="AppointmentId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>
</body>
</html>

Views/Appointments/Details.cshtml
@model ehrmadesimple.Models.Appointment

<!DOCTYPE html>
<html>
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <h2><b>Appointment</b></h2>
        <a class="goback" href="/Clients/Details/@Model.ClientId">< Go Back</a>
    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight row" style= "padding-left:20px !important;">
    <dl class="row">
        <dt class = "col-sm-2" style="padding-bottom:10px;">
            <a href= '@Url.Action("Details", "Bills", new {id = @Model.BillId})'>Review Invoice</a>    
        </dt>
        <dd class = "col-sm-10">
             
        </dd>
        <dt class = "col-sm-2">
            Service
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ServiceType)
        </dd>
        <dt class = "col-sm-2">
            Time
        </dt>
        <dd id= "time" class = "col-sm-10">
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location)
        </dd>
        <dt class = "col-sm-2">
            Diagnosis
        </dt>
    </dl>
    <div class="col-lg-9" style="padding-left:0">
        <br>
        <b>Progress Note</b> &nbsp;
        <a onclick="edit1()" style="color:#007bff">Edit</a> |
        <a onclick="save1()" style="color:#007bff">Save</a>
        <br><br>
        <div class="no-padding col-10" style="width:600px;">
            <div id="ibox1" class="ibox"></div>
            <div class="textarea1" ></div>
        </div>
    </div>
    <br>
    <hr>
    <div class="col-lg-9" style="padding-left:0">
        <b>Psychotheraphy Note</b> &nbsp;
        <a onclick="edit2()" style="color:#007bff">Edit</a> |
        <a onclick="save2()" style="color:#007bff">Save</a>
        <br><br>
        <div class="no-padding col-10" style="width:600px;">
            <div id="ibox2" class="ibox"></div>
            <div class="textarea2"></div>                
        </div>
    </div>
    <div class="col-lg-9" style="padding-left:0;">
        <h4><b>Attachments</b></h4>
        <br>
        <form action="#" class="dropzone" id="dropzoneForm" style="width:200px;">
            <div class="fallback">
                <input name="file" type="file" multiple />
            </div>
        </form> 
    </div>
</div>

<br>
@section Styles {
    <environment names="Development,Staging,Production">
        <link rel="stylesheet" href="~/lib/dropzone/basic.css" />
        <link rel="stylesheet" href="~/lib/dropzone/dropzone.css" />
        <link rel="stylesheet" href="~/lib/summernote/summernote-bs4.css" />
    </environment>

}

@section Scripts {
    <environment names="Development,Staging,Production">
        <script src="~/lib/dropzone/dropzone.js"></script>
        <script src="~/lib/summernote/summernote-bs4.js"></script>
        <script src="~/lib/moment/moment.js"></script>
    </environment>
    <script type="text/javascript">
        onInit();
        Dropzone.options.dropzoneForm = {
            paramName: "file", // The name that will be used to transfer the file
            maxFilesize: 2, // MB
            dictDefaultMessage: "<strong>Drop files here or click to upload. </strong></br>"
        };
        $('#time').append(moment('@Model.Timestamp').format('LLL'));

        function onInit() {
            var html ='<div class="ibox-content col-sm-6">';
            if('@Model.ProgressNote' != '') {
                html +=  '<small>@Model.Timestamp' + '</small><br><strong>' + '@Model.ProgressNote' + '</small>';
            }
            else {
                html += "Click Edit to add progress note "
            }
            html += '</strong></div>';
            $('#ibox1').append(html);

            html ='<div class="ibox-content col-sm-6">';
            if('@Model.PsychoNote' != '') {
                html += '<small>@Model.Timestamp' + '</small><br><strong>' + '@Model.PsychoNote' + '</small>';
            }
            else {
                html += "Click Edit to add psychotherapy note "
            }
            html += '</strong></div>';
            $('#ibox2').append(html);
        }
        
        var edit1 = function() {
            $('#ibox1').remove();
            $('.textarea1').summernote({
            focus: true,
            toolbar:[['style', ['bold', 'italic']],
                ['fontsize', ['fontsize']],
                ['para', ['ul', 'ol', 'paragraph']]],
            height: 150});
        };
        var edit2 = function() {
            $('#ibox2').remove();
            $('.textarea2').summernote({
            focus: true,
            toolbar:[['style', ['bold', 'italic']],
                ['fontsize', ['fontsize']],
                ['para', ['ul', 'ol', 'paragraph']]],
            height: 150});
        };
        var save1 = function() {
            let markup = $('.textarea1').summernote('code');
            let text = markup.replace(/<\/?[^>]+(>|$)/g, "");
            $('.textarea1').summernote('destroy');
            let url = "/api/appointments/" + '@Model.AppointmentId';
            let time = new Date();
            let body = JSON.stringify({"Clientname": '@Model.Clientname', "PsychoNote": '@Model.PsychoNote', "ProgressNote": text}); 
            $.ajax({
                headers: {
                    'Content-Type': 'application/json',
                },
                url: url,
                method: "PUT",
                data: body,
                dataType: 'json',
            });
        };
        var save2 = function() {
            let markup = $('.textarea2').summernote('code');
            let text = markup.replace(/<\/?[^>]+(>|$)/g, "");
            $('.textarea2').summernote('destroy');
            let url = "/api/appointments/" + '@Model.AppointmentId';
            let time = new Date();
            let body = JSON.stringify({"Clientname": '@Model.Clientname', "PsychoNote": text, "ProgressNote": '@Model.ProgressNote'}); 
            $.ajax({
                headers: {
                    'Content-Type': 'application/json',
                },
                url: url,
                method: "PUT",
                data: body,
                dataType: 'json',
            });
        };
        $(document).ready(function () {
            $('.note2').summernote({
                placeholder: '@Model.PsychoNote',
                toolbar:[
                ['style', ['bold', 'italic']],
                ['fontsize', ['fontsize']],
                ['para', ['ul', 'ol', 'paragraph']]],
                height:150
            });
        });

    </script>
}
</html>

Views/Appointments/Edit.cshtml
@model ehrmadesimple.Models.Appointment

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>

<h4>Appointment</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="AppointmentId" />
            <div class="form-group">
                <label asp-for="Clientname" class="control-label"></label>
                <input asp-for="Clientname" class="form-control" />
                <span asp-validation-for="Clientname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ClientId" class="control-label"></label>
                <select asp-for="ClientId" class="form-control" asp-items="ViewBag.ClientId"></select>
                <span asp-validation-for="ClientId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Timestamp" class="control-label"></label>
                <input asp-for="Timestamp" class="form-control" />
                <span asp-validation-for="Timestamp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label"></label>
                <input asp-for="Duration" class="form-control" />
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isAllDay" /> @Html.DisplayNameFor(model => model.isAllDay)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="Location" class="control-label"></label>
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="isRepeating" /> @Html.DisplayNameFor(model => model.isRepeating)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ServiceType" class="control-label"></label>
                <input asp-for="ServiceType" class="form-control" />
                <span asp-validation-for="ServiceType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
</body>
</html>